apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: saikishore/flask-app:latest
          ports:
            - containerPort: 5000
          env:
            - name: DD_AGENT_HOST
              value: "localhost"
            - name: DD_TRACE_ENABLED
              value: "true"
            - name: BUGSNAG_API_KEY
              valueFrom:
                secretKeyRef:
                  name: bugsnag-secret
                  key: 4f52edfe22d9df72f7f4656e0ed651c4
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
